AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
    Default: dev
  pTeamName:
    Description: "Name of the team owning the pipeline (all lowercase, no symbols or spaces)"
    Type: String
    Default: da
  pCuenta:
    Description: "Name of the account owning the pipeline (all lowercase, no symbols or spaces)"
    Type: String
    Default: ecodistribucion
  pProyecto:
    Description: "Name of the project owning the pipeline (all lowercase, no symbols or spaces)"
    Type: String
    Default: misupply
  AWSRegion:
    Type: String
    Description: AWS Region

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "function-${Stage}"
      Description: "Función Lambda que utiliza un rol externo"
      Runtime: python3.9
      MemorySize: 256
      Timeout: 30
      Role: !ImportValue LambdaMisupplyRole-Arn
      CodeUri:
        Bucket: prueba-exampe-josemaria-git/lambda/stage_misupply/src/
      Environment:
        Variables:
          ENVIRONMENT: !Ref Stage
          REGION: !Ref AWSRegion
      Events:
        CronTrigger:
          Type: Schedule
          Properties:
            Schedule: "cron(0 21 * * ? *)" # Se ejecuta todos los días a las 21:00 UTC

  dataWranglerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      ContentUri:
        Bucket: !ImportValue da-ArtifactsBucketlibName
        Key: layers/awswrangler-layer-py3-9.zip
      Description: Data Wrangler Layer for Python 3.9
      LayerName: !Sub awswrangler-layer-py3-9-${Stage}

  requestLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.12
      ContentUri:
        Bucket: !ImportValue da-ArtifactsBucketlibName
        Key: layers/request-layer-py3-12.zip
      Description: Request Layer for Python 3.12
      LayerName: !Sub request-py3-12-${Stage}

Outputs:
  DataWranglerLayerArn:
    Description: ARN of the Data Wrangler Layer
    Value: !Ref dataWranglerLayer
  RequestLayerArn:
    Description: ARN of the Request Layer
    Value: !Ref requestLayer
