AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: Ambiente (dev, qa, prod)
    Default: dev
  pTeamName:
    Description: "Name of the team owning the pipeline (all lowercase, no symbols or spaces)"
    Type: String
    Default: da
  pCuenta:
    Description: "Name of the account owning the pipeline (all lowercase, no symbols or spaces)"
    Type: String
    Default: ecodistribucion
  pProyecto:
    Description: "Name of the project owning the pipeline (all lowercase, no symbols or spaces)"
    Type: String
    Default: misupply
  AWSRegion:
    Type: String
    Description: AWS Region
  LIBbucket:
    Type: String
    Description: Nombre del bucket S3 para el código

Globals:
  Function:
    Runtime: python3.9
    Handler: lambda_function.lambda_handler

Resources:
  rLambdaInvokevent:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri:
        Bucket: !Ref LIBbucket
        Key: lambda/stage_misupply/src/lambda_function.zip
      FunctionName: !Join ['-', ["sdlf", !Ref pTeamName, !Ref pPipeline, "route"]]
      Description: "Gatillado de sm eventuales"
      MemorySize: 256
      Timeout: 500
      Layers:
        - !Ref dataWranglerLayer
        - !Ref requestLayer
      Role: !GetAtt Role.Arn
      Environment:
        Variables:
          ENVIRONMENT: !Ref Stage
          REGION: !Ref AWSRegion
      Events:
        CronTrigger:
          Type: Schedule
          Properties:
            Schedule: "cron(0 21 ? * * *)"

  dataWranglerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      ContentUri:
        Bucket: !Ref LIBbucket
        Key: layers/awswrangler-layer-py3-9.zip
      Description: Data Wrangler Layer for Python 3.9
      LayerName: !Sub awswrangler-layer-py3-9-${Stage}

  requestLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.12
      ContentUri:
        Bucket: !Ref LIBbucket
        Key: layers/request-py3-12.zip
      Description: Request Layer for Python 3.12
      LayerName: !Sub request-py3-12-${Stage}
