AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyQueue.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600 
      
  SQSLambdaMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10  # Número máximo de mensajes que Lambda procesará por invocación
      EventSourceArn: !GetAtt MyQueue.Arn
      FunctionName: !ImportValue MyLambdaFunction.Arn
      Enabled: true