AWSTemplateFormatVersion: 2010-09-09

Resources:
  myQueueLambda:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyQueue.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600 
      


Outputs: 
  myQueueLambda:
    Description: myQueueLambda Arn
    Value: !GetAtt myQueueLambda.Arn
    Export:
      Name: DA-myQueueLambda