name: Sync File to S3

on:
  push:
    branches:
      - main # Solo se ejecutará cuando haya cambios en la rama main

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # 1. Revisa el código del repositorio
    - name: Checkout Repo
      uses: actions/checkout@v2

    # 2. Configura las credenciales de AWS
    - name: connect to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-session-name: awssyncsession
        role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
        aws-region: us-east-1 # Cambia por la región de tu bucket

    # 3. Sube el archivo a S3
    - name: sync bucket
      run: aws s3 cp ./file/ s3://${{secrets.AWS_BUCKET_NAME}} --delete
